services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s

  geoasset-backend:
    image: geoasset-backend
    build:
      # context: ./GeoAsset.Api
      # dockerfile: Dockerfile
      context: .
      dockerfile: GeoAsset.Api/Dockerfile
    ports:
      - "5140:5140"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5140
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=GeoAssetDb;User Id=sa;Password=Password123!;TrustServerCertificate=True"
    depends_on:
      mssql:
        condition: service_healthy

  geoasset-frontend:
    image: geoasset-frontend
    build:
      context: ./geoasset-client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5140"
    ports:
      - "3000:80"
    depends_on:
      - geoasset-backend

volumes:
  mssql_data:
